### PR TITLE
Support Docker

### PR DESCRIPTION
**Pull request by Himura2la**
I needed to run this app locally to use it, and was upset when realized that I need ruby with global packages on my host pc.
Docker image covers this scenario

### CODE REVIEW

**Comment by lelinhtinh** [comment]
Thanks for PR!
I have some problems:

- `0.0.0.0` not working on Windows.
- How to use `jekyll serve --watch` and `jekyll build`?

**Comment by Himura2la** [comment]
1. It's 0.0.0.0 inside the container (Debian buster, if I recall correctly). The host Windows port mapping is managed by Docker
2. Add flags to CMD

**Comment by Himura2la** [comment]
Proof that it works on Windows 
image

**Comment by lelinhtinh** [comment]
I don't think docker configuration should be changed, you can add something like ARG or ENV?

**Comment by Himura2la** [comment]
I don't think it's required to overcomplicate the Dockerfile with ARGs.
Anyone who needs something custom can do
`docker-compose run web bash` and get right into the Debian shell.

**Pull request merged**
